### ISSUE TITLE
Logicblox backend - the head predicate is not correctly returned in the multi-level rules without order

### ISSUE THREAD

**Issue by shek21** [IITDBGroup/gprom#32]
query "Q1(X,Y) :- R(X,Y). Q(X) :- Q1(X,Y)."

lb result:
_(X0, X1) <- _Q1(X0, X1).
_Q1(X,Y) <- R(X,Y).
_Q(X) <- _Q1(X,Y).

**Comment by lordpretzel** [comment]
@shek21 this is not a bug, if you do not specify the answer predicate then GProM uses the first mentioned predicate. Try this:

~~~
Q1(X,Y) :- R(X,Y). Q(X) :- Q1(X,Y). ANS : Q.
~~~


~~~
_(X0) <- _Q(X0).
_Q1(X,Y) <- R(X,Y).
_Q(X) <- _Q1(X,Y).
~~~

**Comment by shek21** [comment]
I got it. Thanks.
