### ISSUE TITLE
problem in configure

### ISSUE THREAD

**Issue by xiaoyingz** [IITDBGroup/gprom#61]
I'm trying to install gprom with option of postgresql backend. I've installed all dependencies including libpq-dev. But after I ran command `./configure --with-libpq=/usr/include/postgresql --disable-oracle`, I got error saying `Unable to find PostgreSQL libpq-fe.h`, but there is a libpq-fe.h in the directory.
<img width="385" alt="Screen Shot 2020-08-03 at 6 31 15 PM" src="https://user-images.githubusercontent.com/47121222/89237023-c5a6dd00-d5b7-11ea-956b-7de1093d9eea.png">
Does any one know how to solve this problem?

**Comment by lordpretzel** [comment]
Hi,

can you try telling GProM where the Postgres headers are by adding the following option to configure:

~~~sh
./configure --with-libpq=/usr/include/postgresql --disable-oracle --with-libpq-headers=THE_LOCATION_OF_POSTGRES_HEADERS
~~~

**Comment by lordpretzel** [comment]
BTW, `--with-libpq` should point to the directory with `libpq.so` not the directory with the headers

**Comment by xiaoyingz** [comment]
Thanks for your help! But I received a BUILD FAILED error, is the website for receiving the request still available?
<img width="570" alt="Screen Shot 2020-08-03 at 9 31 00 PM" src="https://user-images.githubusercontent.com/47121222/89246656-3f979000-d5d1-11ea-99e3-26a3c21f0dab.png">

**Comment by lordpretzel** [comment]
oh, we were aware of this bug (this is for GProM's java bindings. Should be an easy fix, just have to get around to get it done. Until then, if you do not need the Java bindings, add the following to configure

~~~sh
--disable-java
~~~
